### ISSUE TITLE
Error on setup script

### ISSUE THREAD

**Issue by That-Dude** [kalkayan/dotfiles#1]
I'm sure it's something I'm doing wrong but on my freshly install macOS Catalina I'm trying to setup your system and when I get to part where I run setup I'm getting a mapfile error - would appreciate any thoughts you might have.

# this will install all your apps
```
bash ~/setup

setup: line 29: mapfile: command not found
setup: line 35: mapfile: command not found
```

**Comment by kalkayan** [comment]
I think it's because of the bash version, `mapfile` command is available in bash versions 5+. It might be the cause that the `bash ~/setup` is picking the system-installed bash (which may have not been the updated version). 

1. check the bash version if it is above 5
2. In bash run `mapfile` (this is a built-in command and give your a result like) 
```bash
mapfile [-n count] [-O origin] [-s count] [-t] [-u fd]
        [-C callback [-c quantum]] [array]
```
3. and can you tell the output of `which bash` and `bash --version` so I can reproduce this.

This might help you https://stackoverflow.com/questions/61647118/bash-5-mapfile-readarray-command-not-found, if the default bash is 3, we can change the script to update the bash first and then proceed. 

@That-Dude

**Comment by ecrosstexas** [comment]
macOS ships with bash 3.x as default even with Big Sur. I was running into the same issue until I updated to v5.x

@kalkayan

**Comment by That-Dude** [comment]
> macOS ships with bash 3.x as default even with Big Sur. I was running into the same issue until I updated to v5.x
> 
> 
> 
> @kalkayan 

Ok that makes sense. 

I guess not everyone is going to want an updated bash in their dev environment so perhaps a method to workaround using mapfile would be a more pragmatic approach.

I think the external files could be read line by line and evaluated using bash v3.

**Comment by That-Dude** [comment]
Just a quick update - I really love your concept but I needed it work on a fresh install of macOS, so I've re-written your setup script to work with the inbuilt version of bash that macOS includes by default.

I also ended up adding a few feature that suit my needs.

Thanks again
